- resources/views/layouts/sidenav.blade.php
This pr fixes the sidenav items for the admin user account.
> [RTM]: sidenav: fix items for the admin user account

- resources/views/statistics/group-statistics.blade.php
- resources/views/statistics/user-statistics.blade.php
This pr fixes grammar mistakes.
> [RTM]: statistics: fix gramatics

- resources/views/exercises/edit-exercise.blade.php
This pr changes the text in the modal window.
> [RTM]: edit-exercise: change modal window text

- resources/views/groups/show-group.blade.php
- resources/views/home.blade.php
> Fix for admin homepage view and student being able to unassign exercise

- docs/doc.html
This pr updates the GitHub link to the repository in the documentation.
> [RTM]: doc.html: update github link

- resources/views/groups/edit-group.blade.php
- resources/views/profile/edit.blade.php
-[x] Změna obrázku (uživatele, skupiny) -> změnit bez odeslání form a bez refresh
Page does not refresh after submitting an image in a form. If we have any spare time it might be nice to somehow indicate that a file is submitted in said form.
> [RTM] Page not reloading after an image is submitted in a form

- app/Http/Controllers/Administration/ExerciseAdministrationController.php
- app/Http/Controllers/Administration/GroupAdministrationController.php
- app/Http/Controllers/Administration/UserAdministrationController.php
- resources/views/administration/exercise-administration.blade.php
- resources/views/administration/group-administration.blade.php
- resources/views/administration/user-administration.blade.php
This PR adds ajax using jQuery.
> [RTM]: admin: add ajax to admin views

- app/Http/Controllers/Exercises/EditExerciseController.php
- resources/views/exercises/edit-exercise.blade.php
- routes/web.php
This PR adds the ajax for the edit-exercise view.
> [RTM]: Add edit exercise ajax

- app/Http/Controllers/Groups/EditGroupController.php
- resources/views/exercises/edit-exercise.blade.php
- resources/views/groups/edit-group.blade.php
- routes/web.php
This commit adds the ajax for the group editing view.
> [RTM]: edit-group: add ajax

- app/Http/Controllers/ProfileController.php
- resources/views/profile/edit.blade.php
- resources/views/profile/show.blade.php
- routes/web.php
> [RTM] ITU profile

- resources/views/groups/edit-group.blade.php
- resources/views/groups/show-group.blade.php
- resources/views/profile/edit.blade.php
This pr fixes the images proportions.
> [RTM]: Fix images proportions

- app/Http/Controllers/Exercises/EditExerciseController.php
- app/Http/Controllers/Groups/EditGroupController.php
- resources/views/exercises/edit-exercise.blade.php
- resources/views/groups/edit-group.blade.php
- resources/views/groups/show-group.blade.php
- routes/web.php
This pr fixes redirects using url previous too.
> [RTM]: Fix redirects

- public/css/app-custom-extension.css
- resources/views/layouts/header.blade.php
- resources/views/layouts/main.blade.php
- resources/views/layouts/sidenav.blade.php
Texts are bigger, however buttons are not affected. I don't find making buttons font bigger necessary. It also breaks some layout, that would require fixing.
> [RTM] Made font bigger and updated icons for menu

- app/Http/Controllers/Groups/EditGroupController.php
- app/Http/Controllers/Groups/ShowGroupController.php
- resources/views/groups/edit-group.blade.php
- resources/views/groups/show-group.blade.php
- routes/web.php
This PR adds dynamic searching for the show-group view and removes the owner from the list on the edit-group view.
> [RTM]: Add search for show-group and fix owner edit-group

- app/Http/Controllers/Exercises/ExerciseController.php
- resources/views/exercises/myexercises.blade.php
- routes/web.php
Ajax for assigning exercise, filter search and more responsive card printing of individual groups
> [RTM] Itu assign exercise

- app/Http/Controllers/Statistics/GroupStatisticsController.php
- resources/views/statistics/group-statistics.blade.php
- routes/web.php
This pr adds the students searching to the group statistics view.
> [RTM]: group-statistics: add student searching

- public/css/clickable-row.css
- resources/views/administration/exercise-administration.blade.php
- resources/views/administration/group-administration.blade.php
- resources/views/administration/user-administration.blade.php
- resources/views/groups/edit-group.blade.php
- resources/views/groups/show-group.blade.php
- resources/views/layouts/main.blade.php
- resources/views/statistics/group-statistics.blade.php
This pr adds the hover rule for the lists.
> [RTM]: add hover rule for lists

- app/Http/Controllers/Groups/ShowGroupController.php
- resources/views/groups/show-group.blade.php
This pr adds the group owner to the other group description items.
> [RTM]: show-group: add group owner

- resources/views/exercises/edit-exercise.blade.php
This pr adds the showing of the question and answer on hover with an title html attribute.
> [RTM]: edit-exercise: show all question and answer

- resources/views/exercises/edit-exercise.blade.php
This commit makes the space for the answer and question bigger using the textarea tag. At the same time, the option of add many flashcards at the same time is added too.
> [RTM]: Edit exercise textarea

- app/Models/Exercise.php
- database/migrations/2022_11_01_225019_create_exercises_table.php
This PR adds the `show_timer` attribute to the exercises table.
> [RTM]: migrations: add show_timer attribute

- app/Http/Controllers/Exercises/EditExerciseController.php
- resources/views/exercises/edit-exercise.blade.php
This PR adds the option to set if the timer should be visible.
> [RTM]: edit-exercise: add show timer option

- resources/views/home.blade.php
- resources/views/layouts/app.blade.php
- routes/web.php
This pr adds the comments for the files which were authored by the three persons.
> [RTM]: Add doc three authors

- resources/views/administration/exercise-administration.blade.php
- resources/views/administration/group-administration.blade.php
- resources/views/administration/user-administration.blade.php
- resources/views/exercises/edit-exercise.blade.php
- resources/views/groups/edit-group.blade.php
This pr fixes the asynchronous communication for webhosting version.
> [RTM]: fix ajax for webhosting
